server:
  port: 80
  servlet:
    context-path: /ejmc
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DockerTest?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: password

  jpa:    hibernate:      ddl-auto: update #create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate: 
        format_sql: true    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
#      #schema-locations:
#      #- classpath:*.ddl
#      data-locations:
#      - classpath:common_insert.sql
#      continue-on-error: false
      
# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.ejmc.common.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui.html         # Swagger UI 경로 => localhost:8000/demo-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

#logging:
#  level:
#    org:
#      springframework:
#        beans: debug
#        context: debug
#      hibernate:
#        type:
#          descriptor:
#           sql: trace